name: build x64 release ci

on: 
  push:
    branches: [ "dev" ]
  #pull_request:
    #branches: [ "dev" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@main
      - name: Build with MSBuild
        run: msbuild CS2_External\CS2_External.vcxproj /p:Configuration=Ring3 /p:Platform=x64
      - name: Rename EXE to AimStar-Ring3-${{github.sha}}.exe
        run: |
          del AimStar-Ring3-*.exe
          ren AimStar-Ring3.exe AimStar-Ring3-${{github.sha}}.exe
        working-directory: CS2_External\x64\Ring3\
      - name: Upload the output
        uses: actions/upload-artifact@main
        with:
          name: ci
          path: CS2_External\x64\Ring3\*
  buildKernel:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@main
      - name: Build with MSBuild
        run: msbuild CS2_External.sln /p:Configuration=Ring0 /p:Platform=x64
      - name: Rename EXE to AimStar-Ring0-${{github.sha}}.exe
        run: |
          del AimStar-Ring0-*.exe
          ren AimStar-Ring0.exe AimStar-Ring0-${{github.sha}}.exe
        working-directory: x64\Ring0\
      - name: Upload the output
        uses: actions/upload-artifact@main
        with:
          name: cir0
          path: x64\Ring0\*
      - name: Upload the kernel
        uses: actions/upload-artifact@main
        with:
          name: cike
          path: x64\Release\*
  buildllvm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Compile with llvm
        run: msbuild CS2_External\CS2_External.vcxproj /p:Configuration=Ring3 /p:Platform="x64" /p:CLToolExe=clang-cl.exe /p:CLToolPath="C:\Program Files\LLVM\bin"
      - name: Rename EXE to LLVM-AimStar-Ring3-${{github.sha}}.exe
        run: |
          del LLVM-AimStar-Ring3-*.exe
          ren AimStar-Ring3.exe LLVM-AimStar-Ring3-${{github.sha}}.exe
        working-directory: CS2_External\x64\Ring3\
      - name: Upload the output
        uses: actions/upload-artifact@main
        with:
          name: llvm
          path: CS2_External\x64\Ring3\*

        
